<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace GPBMetadata;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        $pool->internalAddGeneratedFile(
            '
’
common.protowallet.v1.insys"ò
CreateWalletä
Req
	branch_id (RbranchId
	member_id (RmemberId
p_id (	RpId
currency (	Rcurrency
username (	Rusername{
Res
success (Rsuccess
code (Rcode2
error (2.google.protobuf.StringValueRerror
data (	Rdata2^
CommonT
CreateWallet!.wallet.v1.insys.CreateWallet.Req!.wallet.v1.insys.CreateWallet.ResB1Zwallet/v1/insys/common Wallet\\V1\\InSys\\Commonbproto3'
        , true);

        static::$is_initialized = true;
    }
}

