<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Wallet\V1\InSys\Common;

if (false) {
    /**
     * This class is deprecated. Use Wallet\V1\InSys\Common\CreateWallet\Req instead.
     * @deprecated
     */
    class CreateWallet_Req {}
}
class_exists(CreateWallet\Req::class);
@trigger_error('Wallet\V1\InSys\Common\CreateWallet_Req is deprecated and will be removed in the next major release. Use Wallet\V1\InSys\Common\CreateWallet\Req instead', E_USER_DEPRECATED);

