<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Wallet\V1\InSys\Common;

if (false) {
    /**
     * This class is deprecated. Use Wallet\V1\InSys\Common\CreateWallet\Res instead.
     * @deprecated
     */
    class CreateWallet_Res {}
}
class_exists(CreateWallet\Res::class);
@trigger_error('Wallet\V1\InSys\Common\CreateWallet_Res is deprecated and will be removed in the next major release. Use Wallet\V1\InSys\Common\CreateWallet\Res instead', E_USER_DEPRECATED);

