<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Wallet\V1\InSys\Common\CreateWallet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 ** Accepted request payload for create wallet service. 
 *
 * Generated from protobuf message <code>wallet.v1.insys.CreateWallet.Req</code>
 */
class Req extends \Google\Protobuf\Internal\Message
{
    /**
     *&#47; ID of branch.
     *
     * Generated from protobuf field <code>uint32 branch_id = 1 [json_name = "branchId"];</code>
     */
    protected $branch_id = 0;
    /**
     *&#47; ID of member.
     *
     * Generated from protobuf field <code>uint64 member_id = 2 [json_name = "memberId"];</code>
     */
    protected $member_id = 0;
    /**
     *&#47; pID of member.
     *
     * Generated from protobuf field <code>string p_id = 3 [json_name = "pId"];</code>
     */
    protected $p_id = '';
    /**
     *&#47; Currency of member.
     *
     * Generated from protobuf field <code>string currency = 4 [json_name = "currency"];</code>
     */
    protected $currency = '';
    /**
     *&#47; Username of member.
     *
     * Generated from protobuf field <code>string username = 5 [json_name = "username"];</code>
     */
    protected $username = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $branch_id
     *          &#47; ID of branch.
     *     @type int|string $member_id
     *          &#47; ID of member.
     *     @type string $p_id
     *          &#47; pID of member.
     *     @type string $currency
     *          &#47; Currency of member.
     *     @type string $username
     *          &#47; Username of member.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common::initOnce();
        parent::__construct($data);
    }

    /**
     *&#47; ID of branch.
     *
     * Generated from protobuf field <code>uint32 branch_id = 1 [json_name = "branchId"];</code>
     * @return int
     */
    public function getBranchId()
    {
        return $this->branch_id;
    }

    /**
     *&#47; ID of branch.
     *
     * Generated from protobuf field <code>uint32 branch_id = 1 [json_name = "branchId"];</code>
     * @param int $var
     * @return $this
     */
    public function setBranchId($var)
    {
        GPBUtil::checkUint32($var);
        $this->branch_id = $var;

        return $this;
    }

    /**
     *&#47; ID of member.
     *
     * Generated from protobuf field <code>uint64 member_id = 2 [json_name = "memberId"];</code>
     * @return int|string
     */
    public function getMemberId()
    {
        return $this->member_id;
    }

    /**
     *&#47; ID of member.
     *
     * Generated from protobuf field <code>uint64 member_id = 2 [json_name = "memberId"];</code>
     * @param int|string $var
     * @return $this
     */
    public function setMemberId($var)
    {
        GPBUtil::checkUint64($var);
        $this->member_id = $var;

        return $this;
    }

    /**
     *&#47; pID of member.
     *
     * Generated from protobuf field <code>string p_id = 3 [json_name = "pId"];</code>
     * @return string
     */
    public function getPId()
    {
        return $this->p_id;
    }

    /**
     *&#47; pID of member.
     *
     * Generated from protobuf field <code>string p_id = 3 [json_name = "pId"];</code>
     * @param string $var
     * @return $this
     */
    public function setPId($var)
    {
        GPBUtil::checkString($var, True);
        $this->p_id = $var;

        return $this;
    }

    /**
     *&#47; Currency of member.
     *
     * Generated from protobuf field <code>string currency = 4 [json_name = "currency"];</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     *&#47; Currency of member.
     *
     * Generated from protobuf field <code>string currency = 4 [json_name = "currency"];</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency = $var;

        return $this;
    }

    /**
     *&#47; Username of member.
     *
     * Generated from protobuf field <code>string username = 5 [json_name = "username"];</code>
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     *&#47; Username of member.
     *
     * Generated from protobuf field <code>string username = 5 [json_name = "username"];</code>
     * @param string $var
     * @return $this
     */
    public function setUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->username = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Req::class, \Wallet\V1\InSys\Common\CreateWallet_Req::class);

