<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syncp.proto

namespace Wallet\V1\ProvSys\Syncp;

if (false) {
    /**
     * This class is deprecated. Use Wallet\V1\ProvSys\Syncp\SyncCredit\Req instead.
     * @deprecated
     */
    class SyncCredit_Req {}
}
class_exists(SyncCredit\Req::class);
@trigger_error('Wallet\V1\ProvSys\Syncp\SyncCredit_Req is deprecated and will be removed in the next major release. Use Wallet\V1\ProvSys\Syncp\SyncCredit\Req instead', E_USER_DEPRECATED);

