<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syncp.proto

namespace Wallet\V1\ProvSys\Syncp;

if (false) {
    /**
     * This class is deprecated. Use Wallet\V1\ProvSys\Syncp\SyncCredit\Data instead.
     * @deprecated
     */
    class SyncCredit_Data {}
}
class_exists(SyncCredit\Data::class);
@trigger_error('Wallet\V1\ProvSys\Syncp\SyncCredit_Data is deprecated and will be removed in the next major release. Use Wallet\V1\ProvSys\Syncp\SyncCredit\Data instead', E_USER_DEPRECATED);

