<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: syncp.proto

namespace Wallet\V1\ProvSys\Syncp;

if (false) {
    /**
     * This class is deprecated. Use Wallet\V1\ProvSys\Syncp\SyncCredit\Res instead.
     * @deprecated
     */
    class SyncCredit_Res {}
}
class_exists(SyncCredit\Res::class);
@trigger_error('Wallet\V1\ProvSys\Syncp\SyncCredit_Res is deprecated and will be removed in the next major release. Use Wallet\V1\ProvSys\Syncp\SyncCredit\Res instead', E_USER_DEPRECATED);

